
package asdf;

import javax.swing.JOptionPane;


//Esta clase se encarga de definir si el usuario desea llevar o comer en el lugar
public class menu2 extends javax.swing.JFrame {
 
    private static String ped;
    /**
     * Creates new form menu2
     */
    public menu2() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llevar = new javax.swing.JLabel();
        restaurante = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(620, 625));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        llevar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llevarMouseClicked(evt);
            }
        });
        getContentPane().add(llevar);
        llevar.setBounds(140, 40, 350, 240);

        restaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restauranteMouseClicked(evt);
            }
        });
        getContentPane().add(restaurante);
        restaurante.setBounds(140, 320, 350, 240);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cuadro_2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void llevarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llevarMouseClicked
       //metodo encargado de definir la condicion de llevar
        ped="llevar";
        pedido.llevarO();
        opener.abrirPedir();
        this.setVisible(false);       
    }//GEN-LAST:event_llevarMouseClicked

    private void restauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restauranteMouseClicked
        //metodo encargado de definir la condicion de comer en el lugar
        ped="restaurante";
        pedido.llevarO();
        opener.abrirPedir();
        this.setVisible(false); 
        
    }//GEN-LAST:event_restauranteMouseClicked
     
    public static String getped() {
        //metodo get encargado de devolver la condicion del pedido
        return ped;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               opener.abrir2();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel llevar;
    private javax.swing.JLabel restaurante;
    // End of variables declaration//GEN-END:variables
}
