
package asdf;

import javax.swing.JOptionPane;


public class pedir extends javax.swing.JFrame {

    //declaracion de atributos de cantidad de pizzas
private static int cP=0;
private static int cjyq=0;
private static int ch=0;
private static int cs=0;
private static int cn=0;
private static int cv=0;
    public pedir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pepe1 = new javax.swing.JCheckBox();
        jamon1 = new javax.swing.JCheckBox();
        hawai1 = new javax.swing.JCheckBox();
        supre1 = new javax.swing.JCheckBox();
        napo1 = new javax.swing.JCheckBox();
        pepe2 = new javax.swing.JCheckBox();
        jamon2 = new javax.swing.JCheckBox();
        hawai2 = new javax.swing.JCheckBox();
        supre2 = new javax.swing.JCheckBox();
        napo2 = new javax.swing.JCheckBox();
        continuar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        veggi1 = new javax.swing.JCheckBox();
        veggi2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(620, 640));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        pepe1.setText("Llevar 1");
        pepe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepe1ActionPerformed(evt);
            }
        });
        getContentPane().add(pepe1);
        pepe1.setBounds(490, 60, 73, 24);

        jamon1.setText("Llevar 1");
        jamon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamon1ActionPerformed(evt);
            }
        });
        getContentPane().add(jamon1);
        jamon1.setBounds(190, 60, 73, 24);

        hawai1.setText("Llevar 1");
        hawai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hawai1ActionPerformed(evt);
            }
        });
        getContentPane().add(hawai1);
        hawai1.setBounds(490, 250, 73, 24);

        supre1.setText("Llevar 1");
        supre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supre1ActionPerformed(evt);
            }
        });
        getContentPane().add(supre1);
        supre1.setBounds(190, 250, 73, 24);

        napo1.setText("Llevar 1");
        napo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                napo1ActionPerformed(evt);
            }
        });
        getContentPane().add(napo1);
        napo1.setBounds(190, 440, 73, 24);

        pepe2.setText("Llevar 2");
        pepe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepe2ActionPerformed(evt);
            }
        });
        getContentPane().add(pepe2);
        pepe2.setBounds(490, 80, 73, 24);

        jamon2.setText("Llevar 2");
        jamon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jamon2ActionPerformed(evt);
            }
        });
        getContentPane().add(jamon2);
        jamon2.setBounds(190, 80, 73, 24);

        hawai2.setText("Llevar 2");
        hawai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hawai2ActionPerformed(evt);
            }
        });
        getContentPane().add(hawai2);
        hawai2.setBounds(490, 270, 73, 24);

        supre2.setText("Llevar 2");
        supre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supre2ActionPerformed(evt);
            }
        });
        getContentPane().add(supre2);
        supre2.setBounds(190, 270, 73, 24);

        napo2.setText("Llevar 2");
        napo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                napo2ActionPerformed(evt);
            }
        });
        getContentPane().add(napo2);
        napo2.setBounds(190, 460, 73, 24);

        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        getContentPane().add(continuar);
        continuar.setBounds(430, 570, 130, 20);

        jLabel5.setText("vegertariana");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(15, 390, 72, 16);

        veggi1.setText("Llevar 1");
        veggi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggi1ActionPerformed(evt);
            }
        });
        getContentPane().add(veggi1);
        veggi1.setBounds(490, 440, 73, 24);

        veggi2.setText("Llevar 2");
        veggi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggi2ActionPerformed(evt);
            }
        });
        getContentPane().add(veggi2);
        veggi2.setBounds(490, 460, 73, 24);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuPedido.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jamon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamon1ActionPerformed
      //boton de 1 pizza de jamon
        if(cjyq==0){
            //si se presiona se define 1 pizza
          cjyq=1;
          
      }else{
            //si el usuario habia seleccionado 2, se desactiva el boton 2 y se activa el 1
         cjyq=1;
         jamon2.setSelected(false);
      }
        
    }//GEN-LAST:event_jamon1ActionPerformed

    private void hawai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hawai1ActionPerformed
      //boton de 1 pizza hawaiana
        if(ch==0){
        ch=1;
       //si se presiona se define 1 pizza
       }else{
           //si el usuario habia seleccionado 2, se desactiva el boton 2 y se activa el 1
       ch=1;
       hawai2.setSelected(false);
       
       }
    }//GEN-LAST:event_hawai1ActionPerformed

    private void pepe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepe2ActionPerformed
       //boton de 2 pizzas peperoni
        if(cP==0){
        cP=2;
       //si se presiona se definen 2 pizzas
       }else{
       cP=2;
       pepe1.setSelected(false);
       //si el usuario habia seleccionado 1, se desactiva el boton 1 y se activa el 2
       }  
       
    }//GEN-LAST:event_pepe2ActionPerformed

    private void napo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_napo2ActionPerformed
        //boton 2 pizzas napolitanas
        if(cn==0){
         cn=2;
        //si se presiona se definen 2 pizzs
        }else{
         cn=2;
        napo1.setSelected(false);
        //si el usuario habia seleccionado 1, se desactiva el boton 1 y se activa el 2
        }
    }//GEN-LAST:event_napo2ActionPerformed

    private void pepe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepe1ActionPerformed
       //boton 1 pizza peperoni
        if(cP==0){
         cP=1;
        //si se presiona se define 1 pizza
        }else{
         cP=1;
        pepe2.setSelected(false);
        //si el usuario habia seleccionado 2, se desactiva el boton 2 y se activa el 1
        }
 
    }//GEN-LAST:event_pepe1ActionPerformed

    private void supre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supre1ActionPerformed
       //boton 1 pizza suprema
        if(cs==0){
         cs=1;
        //si se presiona se define 1 pizza
        }else{
         cs=1;
        supre2.setSelected(false);
        //si el usuario habia seleccionado 2, se desactiva el boton 2 y se activa el 1
        }
    }//GEN-LAST:event_supre1ActionPerformed

    private void napo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_napo1ActionPerformed
       //boton 1 pizza napolitana
        if(cn==0){
         cn=1;
        //si se presiona se define 1 pizza
        }else{
         cn=1;
        napo2.setSelected(false);
        //si el usuario habia seleccionado 2, se desactiva el boton 2 y se activa el 1
        }        
    }//GEN-LAST:event_napo1ActionPerformed

    private void jamon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jamon2ActionPerformed
        //boton 2 pizzas jamon
       if(cjyq==0){
          cjyq=2;
          //si se presiona se definen 2 pizzas
       }else{
         cjyq=2;
         jamon1.setSelected(false);
         //si el usuario habia seleccionado 1, se desactiva el boton 1 y se activa el 2
      }
    }//GEN-LAST:event_jamon2ActionPerformed

    private void hawai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hawai2ActionPerformed
       //boton 2 pizzas hawaianas
        if(cP==0){
         cP=2;
        //si se presionan se definen 2 pizzas
        }else{
         cP=2;
        hawai1.setSelected(false);
        //si el usuario habia seleccionado 1, se desactiva el boton 1 y se activa el 2
        }
    }//GEN-LAST:event_hawai2ActionPerformed

    private void supre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supre2ActionPerformed
       //boton 2 pizzas supremas
        if(cs==0){
         cs=2;
        //si se presiona se definen 2 pizzas 
        }else{
         cs=2;
        supre1.setSelected(false);
        //si el usuario habia seleccionado 1, se desactiva el boton 1 y se activa el 2
        }
    }//GEN-LAST:event_supre2ActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        //boton de continuar
        int comprobar=cP+cjyq+ch+cs+cn+cv;
        
        if (comprobar==0){
        
             JOptionPane.showMessageDialog(rootPane,"ERROR, NO HA ELEGIDO NINGUNA PIZZA!");
            
            
            
            
           
        }else{      
        hawai2.setSelected(false);
        hawai1.setSelected(false);
        jamon2.setSelected(false);
        jamon1.setSelected(false);
        pepe1.setSelected(false);
        pepe2.setSelected(false);
        napo1.setSelected(false);
        napo2.setSelected(false);
        supre2.setSelected(false);
        supre1.setSelected(false); 
        veggi1.setSelected(false);
        veggi2.setSelected(false);
        pedido.cantidades();
        opener.abrirExtras();
        cP=0;
        cjyq=0;
        ch=0;
        cs=0;
        cn=0;
        cv=0;
        this.setVisible(false);
        }

    }//GEN-LAST:event_continuarActionPerformed

    private void veggi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggi1ActionPerformed
        //boton 1 pizza vegetarianas
        if(cv==0){
         cv=1;
        //si se presiona se definen 1 pizzas 
        }else{
         cv=1;
        veggi2.setSelected(false);
        //si el usuario habia seleccionado 2, se desactiva el boton 2 y se activa el 1
        }
    }//GEN-LAST:event_veggi1ActionPerformed

    private void veggi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggi2ActionPerformed
       //boton 2 pizzas vegetarianas
        if(cv==0){
         cv=2;
        //si se presiona se definen 2 pizzas 
        }else{
         cv=2;
        veggi1.setSelected(false);
        //si el usuario habia seleccionado 1, se desactiva el boton 1 y se activa el 2
        }
    }//GEN-LAST:event_veggi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pedir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pedir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pedir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pedir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               opener.abrirPedir();
            }
        });
    }

    public static int getcP() {
        return cP;
    }

    public static int getCjyq() {
        return cjyq;
    }

    public static int getCh() {
        return ch;
    }

    public static int getCs() {
        return cs;
    }

    public static int getCn() {
        return cn;
    }

    public static int getCv() {
        return cv;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuar;
    private javax.swing.JCheckBox hawai1;
    private javax.swing.JCheckBox hawai2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox jamon1;
    private javax.swing.JCheckBox jamon2;
    private javax.swing.JCheckBox napo1;
    private javax.swing.JCheckBox napo2;
    private javax.swing.JCheckBox pepe1;
    private javax.swing.JCheckBox pepe2;
    private javax.swing.JCheckBox supre1;
    private javax.swing.JCheckBox supre2;
    private javax.swing.JCheckBox veggi1;
    private javax.swing.JCheckBox veggi2;
    // End of variables declaration//GEN-END:variables
}
